server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/taskforge
    username: taskforge
    password: secretpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: user-service
