server:
  port: 8081
  servlet:
    context-path: /auth
    forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/taskforge_auth
    username: taskforge
    password: secretpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  security:
    user:
      name: admin
      password: adminpass

jwt:
  secret: "mySuperSecretKeyWithAtLeast32CharactersLong12345"
  expiration-minutes: 1440
  refresh-expiration-days: 7
  issuer: "task-management-system"
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.task_management_system: DEBUG
  file:
    name: logs/auth-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
