server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/taskforge_tasks
    username: taskforge
    password: secretpassword
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:29092
