server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: task-service
          uri: http://task-service:8082
          predicates:
            - Path=/api/tasks/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG