server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: task-service
          uri: http://task-service:8082
          predicates:
            - Path=tasks/**

        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=users/**

      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    reactor.netty: INFO
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"